In [1]:
import numpy as np
arr152 = np.array([20,30,40,50,60])
arr252 = np.array([20,90,40,50,70])
print(arr152)
print(arr252)
print(np.greater(arr152,arr252))
print(np.greater_equal(arr152,arr252))
print(np.less(arr152,arr252))
print(np.less_equal(arr152,arr252))

[20 30 40 50 60]
[20 90 40 50 70]
[False False False False False]
[ True False  True  True False]
[False  True False False  True]
[ True  True  True  True  True]


In [2]:
arr452=np.identity(3)
print('3x3 matrix:')
print(arr452)

3x3 matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
