In [1]:
import numpy as np 



In [2]:
def create_matrix(mc):
    print("\nARRAY "+str(mc)+" Elements : ")
    array_1 = map(int, input().split())
    array_1 = np.array(list(array_1))
    #print(arr)
    print("\nARRAY "+str(mc)+" ,  ROW COLUMN : ")
    row,column = map(int, input().split())
    if(len(array_1)!= (row*column)):
        print("\nRow and Column size not match with total elements !! retry")
        return create_matrix(mc)
    array_1 = array_1.reshape(row,column)
    print("\nARRAY "+str(mc))
    print(array_1)
    return array_1

In [3]:
arr1 = create_matrix(1)
arr2 = create_matrix(2)

if(arr1.shape == arr2.shape):
    print("\nDot product")
    print(np.dot(arr1,arr2))
else:
    print("\nDimensions not matching!")



ARRAY 1 Elements : 


 1 2 3 4



ARRAY 1 ,  ROW COLUMN : 


 2 2



ARRAY 1
[[1 2]
 [3 4]]

ARRAY 2 Elements : 


 1 2 3 4



ARRAY 2 ,  ROW COLUMN : 


 2 2



ARRAY 2
[[1 2]
 [3 4]]

Dot product
[[ 7 10]
 [15 22]]


In [6]:
arr1 = create_matrix(1)
print("Transporse :")
print(arr1.transpose())


ARRAY 1 Elements : 


 1 2 3 4



ARRAY 1 ,  ROW COLUMN : 


 2 2



ARRAY 1
[[1 2]
 [3 4]]
Transporse
[[1 3]
 [2 4]]


In [7]:
arr1 = create_matrix(1)
print("Trace :")
print(arr1.trace())


ARRAY 1 Elements : 


 1 2 3 4



ARRAY 1 ,  ROW COLUMN : 


 2 2



ARRAY 1
[[1 2]
 [3 4]]
Trace
5


In [8]:
arr1 = create_matrix(1)
print("Rank :")
print(np.linalg.matrix_rank(arr1))


ARRAY 1 Elements : 


 1 2 3 4



ARRAY 1 ,  ROW COLUMN : 


 2 2



ARRAY 1
[[1 2]
 [3 4]]
Rank
2


In [9]:
arr1 = create_matrix(1)
print("Determinent :")
print(np.linalg.det(arr1))


ARRAY 1 Elements : 


 1 2 3 4



ARRAY 1 ,  ROW COLUMN : 


 2 2



ARRAY 1
[[1 2]
 [3 4]]
Determinent
-2.0000000000000004


In [10]:
arr1 = create_matrix(1)
print("Inverse :")
print(np.linalg.inv(arr1))


ARRAY 1 Elements : 


 1 2 3 4



ARRAY 1 ,  ROW COLUMN : 


 2 2



ARRAY 1
[[1 2]
 [3 4]]
Inverse
[[-2.   1. ]
 [ 1.5 -0.5]]


In [11]:
arr1 = create_matrix(1)
x,y = np.linalg.eig(arr1)

print("\nE-value : ")
print(x)
print("\nE-vector : ")
print(y)


ARRAY 1 Elements : 


 1 2 3 4



ARRAY 1 ,  ROW COLUMN : 


 2 2



ARRAY 1
[[1 2]
 [3 4]]

E-value : 
[-0.37228132  5.37228132]

E-vector : 
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
